config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :recipes
  root 'recipes#index'
end

app/models/direction.rb
class Direction < ActiveRecord::Base
  belongs_to :recipe

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  	belongs_to :recipe

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
	has_attached_file :image, styles: { medium: "300x300#", thumb: "500x500#" }
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
	validates :name, :description, :image, presence: true

	has_many :ingredients
	has_many :directions
	belongs_to :user
	
	accepts_nested_attributes_for :ingredients, reject_if: :all_blank, allow_destroy: true
	accepts_nested_attributes_for :directions, reject_if: :all_blank, allow_destroy: true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :recipes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!, except: [:index, :show]
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

	def index
		@recipe = Recipe.all
	end

	def new
		@recipe = Recipe.new
	end

	def create
		@recipe = Recipe.new(recipe_params)
		if @recipe.save
			flash[:success] = "Reciped Created"
			redirect_to @recipe
		else
			render 'new'
		end
	end

	def show
		@recipe = Recipe.find(params[:id])
	end

	def edit
		@recipe = Recipe.find(params[:id])
	end

	def update
		@recipe = Recipe.find(params[:id])
		if @recipe.update(recipe_params)
			flash[:success] = "Recipe Updated"
			redirect_to root_path
		else
			render 'edit'
		end
	end

	def destroy
		@recipe = Recipe.find(params[:id])
		@recipe.destroy
		flash[:success] = "Reciped Deleted"
		redirect_to root_url
	end

	private

		def recipe_params
			params.require(:recipe).permit(:name, :description, :image, ingredients_attributes: [:id, :ingredient, :_destroy], directions_attributes: [:id, :steps, :_destroy])
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
%head
	%title Recipes
	= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
	= javascript_include_tag 'application', 'data-turbolinks-track' => true
	= csrf_meta_tags
%body

	%nav.navbar.navbar-default
		.container-fluid
			.navbar-header
				.navbar-brand
					= link_to "Recipes", root_url
			%ul.nav.navbar-nav.navbar-right

				- if user_signed_in?
					%li= link_to "Sign Out", destroy_user_session_path, method: :delete
					%li= link_to "New Recipe", new_recipe_path
				- else
					%li= link_to "Sign In", new_user_session_path
					%li= link_to "Sign Up", new_user_registration_path
	.container	

		- flash.each do |k,v|
			.alert{:class => "alert-#{k}"}= v 
		- flash.each do |k,v|
			.notice 

		= yield

app/views/recipes/_direction_fields.html.haml
.nested-fields
  = f.input :steps
  = link_to_remove_association "remove step", f

app/views/recipes/_form.html.haml
.row
	.col-md-6.col-md-offset-3
		.panel.panel-success
			.panel-heading
				Add New Recipe
			.panel-body
				= simple_form_for @recipe, html: {multipart: true} do |f|
					= f.input :name, input_html: {class: "form-control"}
					= f.input :description, input_html: {class: "form-control"}
					= f.input :image, as: :file, input_html: {class: "form-control"}



					%h3 Ingredients
					#ingredients
						= f.simple_fields_for :ingredients do |ingredient|
							= render 'ingredient_fields', f: ingredient
						.links
							= link_to_add_association 'add ingredient', f, :ingredients, class: "btn btn-default"

					%h3 Directions
					#directions
						= f.simple_fields_for :directions do |direction|
							= render 'direction_fields', f: directions
						.links
							= link_to_add_association 'add direction', f, :directions, class: "btn btn-default"
					%br/
					
					= f.submit "Submit", input_html: {class: "btn btn-default"}

= link_to "Back", root_url, class: "btn btn-default"

app/views/recipes/_ingredient_fields.html.haml
.nested-fields
  = f.input :ingredient
  = link_to_remove_association "remove ingredient", f, class: "btn btn-danger btn-sm"

app/views/recipes/edit.html.haml
= render 'form'

app/views/recipes/index.html.haml
- if Recipe.count == 0
	%p There are currently no recipes

- @recipe.each do |recipe|
	.col-md-3
		.panel.panel-default
			.panel-body.index
				= link_to recipe_path(recipe) do
					= image_tag recipe.image.url(:medium)
			.panel-footer
				%h4.title= link_to recipe.name, recipe_path(recipe)

app/views/recipes/new.html.haml
= render 'form'

app/views/recipes/show.html.haml
.row
	.col-md-12
		- if @recipe.user == current_user
			.btn-toolbar
				.btn-group
					= link_to "Edit", edit_recipe_path, class: "btn btn-default"
					= link_to "Delete", recipe_path, method: :delete, class: "btn btn-default"
				.btn-group
					= link_to "Back", root_url, class: "btn btn-default"
%br
.row.show-top
	.col-md-5
		= image_tag @recipe.image.url(:medium)
	.col-md-7
		.panel.panel-success
			.panel-heading
				%h5.title= @recipe.name
			.panel-body.description
				%p= @recipe.description

.row
	.col-md-6
		.panel.panel-success
			.panel-heading
				%h5 Ingredients
			.panel-body.ingredients
				- @recipe.ingredients.each do |ingredient|
					%li= ingredient.ingredient
	.col-md-6
		.panel.panel-success
			.panel-heading
				%h5 Directions
			.panel-body.directions
				- @recipe.directions.each do |direction|
					%li= direction.steps
		
		